MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
gdal:
  - '3.6.1'
libgdal:
  - '3.6.1'
