{% set name = "qgis" %}
{% set version = "2.18.0" %}
{% set md5 = "861c4af53113158581b42df2acbc3773" %}


package:
  name: qgis
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://qgis.org/downloads/{{ name }}-{{ version }}.tar.bz2
  md5: {{ md5 }}
  patches:
    # QGIS inserts Qt plugin locations into PATH relative to build location
    # This patch fixes it so PATH is relative to install location
    - plugins_path.patch  # [linux]

build:
  number: 1
  skip: true  # [not linux or py3k]

requirements:
  build:
    - cmake
    - flex
    - bison
    - m4
    - python
    - sip
    - expat
    - icu 56.*
    # Qt stack
    - qt 4.8.*
    - pyqt 4.11.*
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    # GDAL stack
    - gdal 2.1.*
    - geos 3.4.*
    - proj4 4.9.3
    # GSL for georeferencer
    - gsl
    - sqlite 3.13.*
    - libspatialindex
    - libspatialite
    # For PostgreSQL support
    - postgresql
    - psycopg2
  run:
    - python
    - icu 56.*
    - qt 4.8.*
    - pyqt 4.11.*
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    - gdal 2.1.*
    - geos 3.4.*
    - proj4 4.9.3
    - gsl
    - sqlite 3.13.*
    - libspatialindex
    - libspatialite
    - psycopg2
    - postgresql
    # Runtime deps QGIS can include internally
    - future
    - dateutil
    - httplib2
    - jinja2
    - markupsafe
    - nose
    - owslib
    - pygments
    - pytz
    - six
    - pyyaml
    - yaml

test:
  commands:
    - conda inspect linkages -p $PREFIX pynio  # [not win]
    - conda inspect objects -p $PREFIX pynio  # [osx]

about:
  home: http://qgis.org/
  license: GPLv2
  license_file: COPYING
  summary: 'A free and open source Geographic Information System (GIS).'
  description: |
    QGIS is a user friendly Open Source Geographic Information System (GIS)
    licensed under the GNU General Public License. QGIS is an official
    project of the Open Source Geospatial Foundation (OSGeo). It runs on
    Linux, Unix, Mac OSX, Windows and Android and supports numerous vector,
    raster, and database formats and functionalities.
  doc_url: https://www.qgis.org/en/docs/index.html
  dev_url: https://github.com/qgis/QGIS

extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
