{% set name = "qgis" %}
{% set version = "3.4.5" %}

package:
  name: qgis
  version: {{ version }}

source:
  url: https://qgis.org/downloads/{{ name }}-{{ version }}.tar.bz2
  sha256: fd753aec10e6430c090b4800eb1424a853df63b25f6b992bb31c6df49f0cdc57
  patches:
    # QGIS needs to #include <functional> for GCC7 & VC14, at least
    - gcc7-function-include.patch
    # QGIS inserts Qt plugin locations into PATH relative to build location
    # This patch fixes it so PATH is relative to install location
    - plugins_path.patch  # [linux]
    # Mac
    - mac_patch_dark_theme.patch  # [osx]
    # by default looks for pyrcc5.bat on Windows, but we have pyrcc5.exe
    - pyrcc.patch  # [win]
    # gets the wrong geos lib
    - geoscmake.patch  # [win]
    # don't try and install MSVC runtime libs as they already exist
    - CMakeLists.nosyslibs.patch  # [win]

build:
  number: 1000
  skip: true  # [py2k]

requirements:
  build:
    - cmake
    - ninja
    - m2-flex  # [win]
    - m2-bison  # [win]
    - m2-m4  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
  host:
    - python
    - six
    - flex  # [unix]
    - bison  # [unix]
    - m4  # [unix]
    - pkgconfig
    - sip
    - expat
    - icu
    - libzip
    - libtasn1  # [osx]
    # Qt stack.
    - qt
    - pyqt
    - qtwebkit  # [osx]
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    - qtkeychain
    - qtlocation
    # included in win-64 Qt already but needed for linux/osx
    - qtserialport  # [unix]
    # GDAL stack.
    - gdal
    - geos
    - proj4
    # GSL for georeferencer.
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    # For PostgreSQL support.
    - postgresql
    - psycopg2
    # XOrg CDT packages used in qt-feedstock
    - xorg-libice      # [linux]
    - xorg-libsm       # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxt       # [linux]
    - xorg-inputproto  # [linux]
    - gtk2  # [linux]
  run:
    - python
    - icu
    - libzip
    - libtasn1  # [osx]
    - qt
    - pyqt
    - qtwebkit  # [osx]
    - qscintilla2
    - qca
    - qjson
    - qwt
    - qwtpolar
    - qtkeychain
    - qtlocation
    - qtserialport  # [unix]
    - gdal
    - geos
    - proj4
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    - psycopg2
    - postgresql
    # Runtime Python library deps
    - python-dateutil
    - future
    - httplib2
    - jinja2
    - markupsafe
    - mock
    - nose2
    - owslib
    - plotly
    - pygments
    - pyproj
    - requests
    - six
    - sip
    - pytz
    - pyyaml
    - yaml
    - owslib
    # XOrg CDT packages used in qt-feedstock
    - xorg-libice      # [linux]
    - xorg-libsm       # [linux]
    - xorg-libx11      # [linux]
    - xorg-libxext     # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxt       # [linux]
    - xorg-inputproto  # [linux]
    - gtk2  # [linux]

test:
  commands:
    # cannot execute this at the moment:
    # raise ImportError('This package should not be accessible on Python 3.
    # - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://qgis.org/
  license: GPL-2.0
  license_file: COPYING
  summary: 'A free and open source Geographic Information System (GIS).'
  description: |
    QGIS is a user friendly Open Source Geographic Information System (GIS)
    licensed under the GNU General Public License. QGIS is an official
    project of the Open Source Geospatial Foundation (OSGeo). It runs on
    Linux, Unix, Mac OSX, Windows and Android and supports numerous vector,
    raster, and database formats and functionalities.
  doc_url: https://www.qgis.org/en/docs/index.html
  dev_url: https://github.com/qgis/QGIS

extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
