travis:
  secure:
    BINSTAR_TOKEN: pQd7ng2SscU+4xW55G5kS2tjNn2MbO+wm8jfGAqaEehM7wNsj/GsZiK4q47H6i589sm7uVWUCO7DPaNyJmjBmTI/WN1tk9ozxuVKIPVj0nFwPZSrfaFthhUsNBs9MhuikfT522iNkuJz2jALVq3Ix4fQzwdBw+xEPnTxNKZF+7RgiEFNG97gM7uIJpbv4Wrr46mvpoXrfy6r940eb/vlvfRmwh8KZOFRAuuYqMzjQWNw71trx39cFXouTsC2jHbI1voi90y/wsSYK1c/qy5ZTCkvh0MjPz0nM7KJ9nU99X/rsb6oMMqGLumeERWgtnQwfmgnOEPp7P7boNlEzVBGLnOrDdhMghBOr1Q71mRSBdHMB3k/oZyXPTdjlWOjnOmoz+3QBTgUs/ghqQm2hJDGTFkFqgswXpHWkdu8R2QWm8ZvrudokhxxF1FZwwo2SXeI/GEFBLIzht8P0EiuzWL5kc5slcVzlvcZPV5LRNc9MKKJmAr+YXsxSKfPMhBeMTfckyGWlF6Yj8TTKY3m9/GfRDsVfoYaX2Po4xNou5+Cj3JOQDUeir8G8vcNKszTu9ndk/rr8kREhtvXDofJT3YmlbfLGBWftwyHsmmWCDhOW+IgsWPWzU2u1Qe5Eur2e32Agyx86i2DurUgshPC/2XUzlaqpvDxfxAzesz5IPNEack=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
